Metrics webapp
moise-mulungu/metrics-webapp-makeup pull request #1
Opened 2022-04-28 22:30 UTC by moise-mulungu

On this milestone, I:
- Chose a beauty Makeup API for this App
- Created two main pages for my App
- Installed React-redux with their dependencies
- Created components
- Setup the basic structure for my App
- Added functionalities to my main pages
- Created both unit and integration testings.
- Updated the README file 
- Recorded Loom video.

2022-04-29 11:48 UTC, uwadonat requested changes
Hi **@[moise-mulungu](https://github.com/moise-mulungu),** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://user-images.githubusercontent.com/65860678/165938597-af69c157-ce6c-421f-9ede-0bd46f0bc84e.gif)


## Highlights
- Your commit and pull request messages are very descriptive ✔️
- No linter errors ✔️
- Your code is well organised and clean ✔️

## Required Changes ♻️

- [ ] Make sure your presentation shows code that you find interesting or you are proud of making.

- [ ] _Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 11:48 UTC, uwadonat commented on src/__tests__/makeups.test.js
> +  expect(makeupReducer(previousState, getAllFoundations())).toBeDefined();
- [ ] Let's add more unit tests for several components of the app and some pure functions in Redux code.

2022-04-30 13:40 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️

![](https://media.giphy.com/media/cE02lboc8JPO/giphy.gif)
@ ✋🏼 
#### Great work on making the changes requested by a previous reviewer 👏 
#### You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
___
### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._
- [ ] Like the last reviewer said your presentation should include some code that you are proud of it. You showed only the website. [Requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=you%20should%20also%20highlight%20some%20interesting%20piece%20of%20code%20or%20something%20you%20built%20that%20you%20are%20very%20proud%20of.)
___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏

![almost](https://media.giphy.com/media/oHwvp6bEuiog0bxg2P/giphy.gif)

___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._
___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-04-30 17:15 UTC, elmar8287 approved these changes
Hi, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 18:50 UTC, merged